theme: jekyll-theme-cayman
title: Privacy-Preserving Federated Learning for Healthcare
description: An innovative approach to enabling collaborative AI across healthcare institutions without sharing sensitive patient data
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/komal-shahid/federated-healthcare-ai
  repository_name: federated-healthcare-ai
  owner_name: Komal Shahid
google_analytics: 